### ISSUE TITLE
Does noxim support adaptive routing ? 

### ISSUE THREAD

**Issue by AndrewGigie** [davidepatti/noxim#10]
When i use the command as mentioned in Manual. It says invalid usage.

**Comment by davidepatti** [comment]
which command exactly ?

**Comment by AndrewGigie** [comment]
-routing fullyadaptive
The fully adaptive routing algorithm.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DDB4FAA8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

On Mon, May 23, 2016 at 3:36 PM, Davide Patti <notifications@github.com>
wrote:

> which command exactly ?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/davidepatti/noxim/issues/10#issuecomment-220939573>
>



-- 

Andrew Gigie

MT 15086(M. Tech ECE)


(A State University established by Govt. of NCT Delhi),

1st Floor, Academic Building,

Okhla Phase-3, (Nr. Govind Puri Metro Station)

New Delhi-110020

**Comment by davidepatti** [comment]
Manual is related to old/deprecated version. Anyway,  fullyadaptive was not deadlock free and will not be ported on current version. Please refer to ./noxim -help and the default_config.yaml in config_examples

**Comment by vnd2586** [comment]
Hello prof. Davidepatti et.al,
Noxim can only use for topo mesh? is it right?
many thanks!

**Comment by davidepatti** [comment]
If you don't change the code (e.g. signals mapping when creating the NoC), the mesh is assumed as deafult. However, signals/port mapping is done dynamically, so you could implement your own topologies (changing also routing of course).
Anyways, even leaving the code as it is, the usage of radiohub allows a small-world style network.
