### ISSUE TITLE
Table Based Routing Algorithm Doesn't Work

### ISSUE THREAD

**Issue by lchang256** [davidepatti/noxim#106]
Has anyone tried routing table based sim?  

I created a simple mesh with a routing table per the format in GlobalRoutingTable.cpp.

However, simulation always crashes with file not found.

Debug shows the file name and location being parsed correctly by the simulator, but message is always file not found.

Is there a directory where the file is expected?

Thanks

**Comment by van-namdinh** [comment]
Hi @Ichang256
Could you share your configuration file to discuss more.
email me to email vndprogramminges@gmail.com
BR!

**Comment by lchang256** [comment]
I have figured out the issue.  There were 2 issues:  1. Placement of routing table needs to be in bin directory 2. The routing table format needs to follow  format in issue #64 and not from the code example fields.
