### ISSUE TITLE
error with noxim_explorer

### ISSUE THREAD

**Issue by Sangs19** [davidepatti/noxim#111]
Getting above  while executing make command for noxim_explorer and following is the error  with command ./noxim_explorer sim.cfg

g++ -std=c++11 -O2  -c noxim_explorer.cpp -o noxim_explorer.o
noxim_explorer.cpp: In function ‘bool RunSimulation(const string&, const string&, TSimulationResults&, std::__cxx11::string&)’:
noxim_explorer.cpp:642:9: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
   system(cmd.c_str());
   ~~~~~~^~~~~~~~~~~~~
noxim_explorer.cpp:647:9: warning: ignoring return value of ‘int system(const char*)’, declared with attribute warn_unused_result [-Wunused-result]
   system(rm_cmd.c_str());
   ~~~~~~^~~~~~~~~~~~~~~~
g++ -std=c++11 -O2  noxim_explorer.o -o noxim_explorer




# Exploring configuration space sim.cfg
# simulation 1 of 100
../bin/noxim -pir 0.001 poisson  -sim 100000 -warmup 10000 -size 8 8 -buffer 4  -routing XY -sel random -topology MESH -dimx 8 -dimy 8  >./.noxim_explorer.tmp 2>&1
Error: Output file ./.noxim_explorer.tmp corrupted

**Comment by davidepatti** [comment]
hi,
try to manually launch the single line of noxim that is being executed...
./bin/noxim -pir 0.001 poisson  -sim 100000 -warmup 10000 -size 8 8 -buffer 4  -routing XY -sel random -topology MESH -dimx 8 -dimy 8
