### ISSUE TITLE
Dos Attack Simulation

### ISSUE THREAD

**Issue by AntiHackerir** [davidepatti/noxim#113]
I want to simulate a denial of service attack in the Noxim
But when I write traffic table
For example:
0 399 1.0
The answer of the simulator less total energy than random traffic!
While he should total energy more
what is the problem ?

My command is :
./noxim -winoc -wirxsleep -pir 1.0  poisson -sim 100000 -warmup 10000 -traffic table pattern -size 64 64 -flit 32 -buffer 4 -config ../config_examples/default_configMesh.yaml -power power.yaml -routing XY -topology MESH -dimx 20 -dimy 20 >/home/uni/Desktop/WiNoc_UnderAttack.tmp 2>&1

and my traffic table : 
0 399
1 399
2 399

And the result is this

5.18798e-05

While in random traffic

Is 5.98798e-05

!!!!

**Comment by davidepatti** [comment]
It's not true that if you make a huge traffic towards a single node the energy will be necessarily bigger... for example, this may lead to congestion, where every packet is blocked waiting to be processed in queue -> less energy
