### ISSUE TITLE
How to deactivate a link or a node in Noxim

### ISSUE THREAD

**Issue by ishakhari** [davidepatti/noxim#115]
Hello professor, I am looking for a solution to deactivate a link or a node in Noxim. In the aim of implementing a fault-tolerant routing algorithm.
In other way, I want to create some scenarios where some link are down. 
I founded this in some forums but I didn't know where I have to add this code.
// To deactivate the router 0,0
`for ( int d = 0  ; d < DIRECTIONS ; d++ ) {`
`n->t[0][0]->r->reservation_table.Invalidate(d); }`

// To deactivate link
`for ( int i = 0  ; i < NoximGlobalParams::mesh_dim_x   ; i++ ) {`
`for ( int d = 0  ; d < DIRECTIONS ; d++ ) {`
`t[i][0]->r->reservation_table.Invalidate(d); }}`

Furthermore, if I successfully deactivate a link, how can I test it in my algorithm.

**Comment by davidepatti** [comment]
Just make a simple network and use enable the DEBUG in Makefile to see the logs.
