### ISSUE TITLE
Error in the function: NoximTile *NoximNoC::searchNode(const int id) 

### ISSUE THREAD

**Issue by Bhagya-laxmi** [davidepatti/noxim#116]
Dear Professor,

I am using the Noxim-2010 version for my project and I find that "searchNode" function in NoximTile throws an error.
The error is because of the return value.

```
NoximTile *NoximNoC::searchNode(const int id) const
{
    for (int i = 0; i < NoximGlobalParams::mesh_dim_x; i++)
	for (int j = 0; j < NoximGlobalParams::mesh_dim_y; j++)
	    if (t[i][j]->r->local_id == id)
		return t[i][j];

    return false;
}
```
I am wondering whether the mistake is from my side so that it can be rectified.

**Comment by davidepatti** [comment]
Noxim 2010 is currently unsupported.
