### ISSUE TITLE
Static Code Analysis

### ISSUE THREAD

**Issue by Bugman-creator** [davidepatti/noxim#117]
This is for a class project. A Static Code Analysis Tool was run on your project and filtered to only include correct findings
Please find attached the file containing the errors. This file includes the error type, as well as the files and lines where the errors occur

[noximSCAResults.txt](https://github.com/davidepatti/noxim/files/5578605/noximSCAResults.txt)

**Comment by davidepatti** [comment]
Thank you very much!
