### ISSUE TITLE
Error with TABLE BASED routing

### ISSUE THREAD

**Issue by udaymallappa** [davidepatti/noxim#130]
I could implement custom traffic with ease, but when implementing custom routing, I find some issues with syntax.
Here is an example routing table.txt used by me  for two flows, one from node 58 to node 53, other from node 18 to node 36. Mesh is 8x8 and (space at the start of each line).

 58 58->58 53 58->59,
 59 58->59 53 59->60,
 60 59->60 53 60->61,
 53 61->53 53 53->53,
 18 18->18 36 18->19,
 19 18->19 36 19->20,
 20 19->20 36 20->28,
 36 28->36 36 36->36,

![image](https://user-images.githubusercontent.com/37677263/138060250-b7215bde-4459-4d8a-8815-1088bbd633c2.png)

**Comment by NishanthAiyappa** [comment]
can you please tell what the bug was?
