### ISSUE TITLE
How adding a fault to the node?

### ISSUE THREAD

**Issue by taadaal** [davidepatti/noxim#139]
Hi
I implemented the XY-YX algorithm in Noxim. As you know, this algorithm is a fault-tolerance routing algorithm.
What code or function should I add to the Router.cpp file to cause a fault in a node?
In other sources, I found the XY-YX Router.cpp that related to the old version, and I made changes like this file, but I got a lot of errors.
Could I reference a fault to the routing algorithm with a function?
[Fault Tolerant Dynamic XY-YX Routing Algorithm for Network On-Chip Architecture.pdf](https://github.com/davidepatti/noxim/files/8839940/Fault.Tolerant.Dynamic.XY-YX.Routing.Algorithm.for.Network.On-Chip.Architecture.pdf)

**Comment by davidepatti** [comment]
the description is too generic... what kind of fault? being unable to route? forever or temporary?
Anyway you could just add a boolean representing the status (e.g., true=working, false = fault) and then putting in AND to whatever piece of code implements the faulty part of the router.
