### ISSUE TITLE
Issue with Negative-First

### ISSUE THREAD

**Issue by amircharif** [davidepatti/noxim#14]
Hello,

Regarding the current implementation of Negative-first in Noxim: Packets headed South-East are routed using XY, i.e. Positive then negative, which violates the rules of Negative-first and may induce deadlocks.

Possible fix:

if (destination.x < current.x || destination.y > current.y) // check negative directions first
{
    if (destination.x < current.x) directions.push_back(DIRECTION_WEST);
    if (destination.y > current.y) directions.push_back(DIRECTION_SOUTH);
} else if  (destination.x > current.x || destination.y < current.y) {
    if (destination.x > current.x) directions.push_back(DIRECTION_EAST);
    if (destination.y < current.y) directions.push_back(DIRECTION_NORTH);
} else 
    directions.push_back(DIRECTION_LOCAL);

Best regards

**Comment by davidepatti** [comment]
you seem to be right 👍 
I am going to apply your fix in a few minutes
Thank you very much
