### ISSUE TITLE
Assertion Error

### ISSUE THREAD

**Issue by taadaal** [davidepatti/noxim#140]
Hi, I am trying to simulate this file 
[porposed_config.docx](https://github.com/davidepatti/noxim/files/8986058/porposed_config.docx)
everything ok with other traffic but when i simulated with TRAFFIC_BIT_REVERSAL, TRAFFIC_SHUFFLE, TRAFFIC_BUTTERFLY, I get this error 
![Assertion Error](https://user-images.githubusercontent.com/90440707/175801916-6855d10a-254d-44d3-98d6-53f2b2a77950.PNG)
What's the problem?

**Comment by taadaal** [comment]
Thanks for responding dear professor,
Yes I Try 10x10, and the problem is from "Utils.h" file this part:
![Capture](https://user-images.githubusercontent.com/90440707/175995324-85f860ed-e45d-42fb-8662-cdd3f0d8d3a6.PNG)
How can I fix this problem? Which part of the Noxim must be changed?

**Comment by davidepatti** [comment]
what don't you just put some print messages to debug the values...

**Comment by taadaal** [comment]
I didn't understand the point. What are print messages?

**Comment by theblueskies** [comment]
@taadaal You can use `cout` to print messages. That'll help you to see the transition of states. From the error you have pasted, it looks like your modification has caused it to exceed `mesh_dim_y` . Meaning if the max value of y dimension is 10, your changes have just gone above 10 and the assertion has failed.
