### ISSUE TITLE
Received/Ideal flits ratio parameter

### ISSUE THREAD

**Issue by taadaal** [davidepatti/noxim#141]
What is the "Received/Ideal flits ratio" parameter doing in the network? And in the different rates of injections, for example, 0.1 to 0.5, this number is closer to zero. Is this a good result?
![Capture](https://user-images.githubusercontent.com/90440707/179260097-d5f23ef2-1d4d-47c7-b0e0-69861ace43e9.PNG)

**Comment by davidepatti** [comment]
No, the more is near 1, the better it is. Look at the code, it is the expected flits to be delivered according to a specific pir VS what is actually delivered.

**Comment by taadaal** [comment]
Thanks for responding.
