### ISSUE TITLE
Docker based build 

### ISSUE THREAD

**Issue by theblueskies** [davidepatti/noxim#144]
How does a Docker based build sound? It would - 
1. Make it OS agnostic as long as docker is installed. A shell script can also help install docker on the fly.
2. Uniformity on packages used. So that any deltas in packages do not cause any unwanted side effects.

**Comment by davidepatti** [comment]
yes, I agree with that. A docker or even a snap package for ubuntu would help a lot.
Just didn't have the time to allocate to such task. Any contribution is welcome!
