### ISSUE TITLE
Routing Table's format

### ISSUE THREAD

**Issue by Pi-Hsung** [davidepatti/noxim#147]
Hi, could you provide the format of user defined routing table? i try all the format in issuses discussion, but it still can't work 
the format i write is 
0 0->0 5 0->1,
1 1->5 5 1->5,
but i got the error "noxim: ../src/routingAlgorithms/Routing_TABLE_BASED.cpp:28: virtual std::vector<int> Routing_TABLE_BASED::route(Router*, const RouteData&): Assertion `ao.size() > 0' failed."
Please, could anyone give me some advices?

**Comment by davidepatti** [comment]
Just read the code to to see how the scan of the input is done
