### ISSUE TITLE
Different hold times for different hubs

### ISSUE THREAD

**Issue by lord-tarun** [davidepatti/noxim#152]
Hello all,
I am new to Noxim and need to modify the MAC policy of the wireless channel in Noxim such that I can assign varying hold times for each of the wireless hubs. However, as  seen below, the closest config to my requirement is the second one, which assigns a constant hold time for all the hubs. What files should I modify to achieve this? 
>  
    # mac policies:

    # who has the token releas only when a complete packet has
    # been sent
        #[TOKEN_PACKET]

    # who has the token, release only after a fixed number of
    # cycles, even no transmission is occurring
        #[TOKEN_HOLD, num_hold_cycles]

    # who has the token, holds the packet until needed for
    # transmissions, until a max number of cycles is reached
        #[TOKEN_MAX_HOLD, max_hold_cycles]

        mac_policy: [TOKEN_PACKET]

**Comment by davidepatti** [comment]
Just track that variable num_hold_cycles in the code, and check when it is used
