### ISSUE TITLE
Results in .m file

### ISSUE THREAD

**Issue by masi00** [davidepatti/noxim#20]
Hello 
How can I see more results in Matlab with running  the following command line:
./noxim -config ../config_examples/default_config.yaml

in the old version of Noxim, we can see this results with m.file.

**Comment by davidepatti** [comment]
I'm not sure about your question. The output of Noxim is matlab compliant

**Comment by masi00** [comment]
hi, davidepatti.
how can see the output of WiNoxim in Matlab environment? contains all output parameters ( such as delay, throughput;[max, average] with different values of Packet Injection Rate (pir)?
