### ISSUE TITLE
for routing algorithm other then XY and DYAD 

### ISSUE THREAD

**Issue by priya0777** [davidepatti/noxim#22]
noxim: ../src/Power.cpp:104: void Power::configureRouter(int, int, int, std::__cxx11::string, std::__cxx11::string): Assertion `GlobalParams::power_configuration.routerPowerConfig.routing_algorithm_pm.find(routing_function) != GlobalParams::power_configuration.routerPowerConfig.routing_algorithm_pm.end()' failed.
Aborted (core dumped)

i am getting this error

**Comment by davidepatti** [comment]
which YAML configuration file are you using?

**Comment by davidepatti** [comment]
The above message is usually related to a missing entry in the power.yaml file.
