### ISSUE TITLE
How to add wakeup latency to Router?

### ISSUE THREAD

**Issue by sourockg** [davidepatti/noxim#28]
I am trying to power gate router and then power on. There will be few cycles latency before power gated router starts working. Would like to know how we can add latency in the simulation for only one object such as router and how we can keep track of no. of cycles executed till any point of time?

**Comment by davidepatti** [comment]
why don't you just annotate the sc_time_stamp().to_double() and then change some router state variable so that no other action it's taken in the meanwhile.
