### ISSUE TITLE
Running Config file and Facing Error.

### ISSUE THREAD

**Issue by Rachel9595** [davidepatti/noxim#30]
I've tried to use another topology  (not mesh) in Noxim. So I've changed some codes in source code files .After compiling Noxim, I tried to run default_config.yaml, but I was faced with this error:
....
Loading configuration from"/home/..."... Done
Loading power from file "power.yaml"... Done
noxim: libs/system-2.3.1/include/sysc/communication/sc_port.h"541" void sc_core::sc_port_b<IF>::add_interface(sc_core::sc_interface*) [with IF = sc_core::sc_signal_in_if<Flit>] Assertion 'iface !- 0' failed.
Aborted (core dumped)

I would be very thankful if you could tell me the reason of this error, and how I can fix it.
Thanks alot
Rachel

**Comment by davidepatti** [comment]
There are no elements to have any clue about the issue. Please provide a detailed list of the modifications. Anyway, advanced modifications of Noxim source code are not usually supported by our team due a lack of time...
