### ISSUE TITLE
3D NoC suport

### ISSUE THREAD

**Issue by cace15** [davidepatti/noxim#32]
Hi prof. Davide Patti,
How can simulate a 3D NoC with Noxim?
Is Noxim support through-silicon via (TSV) links?

Thanks a lot

**Comment by davidepatti** [comment]
You should modify the source code and the interconnection between tiles. It's not an easy thing to explain with a few lines comment, you should add another connection and related I/O systemC ports and signals. Take inspiration from existing directions, e.g. "local", and imagine TSV as a new direction.

**Comment by cace15** [comment]
Thanks a lot Professor Davide Patti.
