### ISSUE TITLE
Power consumption of routing algorithms

### ISSUE THREAD

**Issue by Rachel9595** [davidepatti/noxim#34]
Hi,
In "bin/power.yaml" , Static and Dynamic power consumption are defined for XY and DYAD routing algorithms.
Would you please explain a little more about the mechanism of computation of power consumption for
a routing algorithm?
Thanks a lot

**Comment by Rachel9595** [comment]
Or please introduce some useful and related documents about computation of power consumption of a routing algorithm?
Thank you..

**Comment by davidepatti** [comment]
We just drafted an simple hdl implementation of them a performed a power estimation. Anyway, if you think about routing logic, we are talking  of a few hardware elements.
