### ISSUE TITLE
How to run Noxim in Eclipse linux or MS Visual Studio

### ISSUE THREAD

**Issue by Afiruzan** [davidepatti/noxim#35]
Dear Prof. Davide Patti,
Please let me know that how can I run Noxim in Eclipse linux or MS Visual Studio 2013?
Thanks a lot

**Comment by davidepatti** [comment]
I would never recommend to do that. Noxim is designed to be a simple command line tool, with a simple source code directory and standard multi-platform makefiles.
So please just use the latest GNU/Linux distribution, and if you use Ubuntu Linux you could also enjoy the automatic installation script that does everything needed for you.
