### ISSUE TITLE
What is the best traffic pattern to test the routing algorithm?

### ISSUE THREAD

**Issue by mamadymadan** [davidepatti/noxim#36]
I need to a application specific traffic pattern. I want to bench mark my routing algorithm.what is the best choice?
What is apsra traffic pattern?

**Comment by davidepatti** [comment]
Please refer to the main noxim paper cited in the homepage to have details/references about routing  algorithms. As for ASPRA, see  https://www.computer.org/csdl/trans/td/2009/03/ttd2009030316-abs.html

**Comment by mamadymadan** [comment]
Thank you for your help. I have already read this article but now I need a data set of different applications so I can examine my algorithm.
In fact, I need a data set that can be cited in the articles.
Are there any data set with these specifications?
Thanks for your follow up.

**Comment by Sissima** [comment]
You can find in this paper a study mentioning the most used traffic patterns to test NoC routing algorithms.
[NoC routing protocols – objective-based classification](http://www.sciencedirect.com/science/article/pii/S1383762116300303)
