### ISSUE TITLE
Mapping in Noxim

### ISSUE THREAD

**Issue by mehranzadeh** [davidepatti/noxim#37]
Hi,
I'm going to implement a new mapping algorithm in the Noxim for a research project.
Please guide me how do I use the Noxim for mapping purpose.

Thanks in advance

**Comment by mpalesi** [comment]
Hello Amin,

Do you mind to add additional details to your question? Mapping is a very
wide concept that can be tackled at different levels of abstraction and
granularities. It is very difficult to reply your question without
additional details of what you have in mind.

Regards,

Mau
