### ISSUE TITLE
Error; running a new routing algorithm.

### ISSUE THREAD

**Issue by setat** [davidepatti/noxim#38]
Hi,
I want to try a new routing algorithm; I've changed XY routing (in order not to get error of power) and I ran the command below:
./noxim -config ../config_examples/default_config.yaml

and got this error:

        SystemC 2.3.1-Accellera --- Apr 12 2017 10:06:33
        Copyright (c) 1996-2014 by all Contributors,
        ALL RIGHTS RESERVED

                Noxim - the NoC Simulator
                (C) University of Catania

Loading configuration from file "../config_examples/default_config.yaml"... Done
Loading power configurations from file "power.yaml"... Done
Reset for 1000 cycles...
 done! Now running for 10000 cycles...

Error: (E549) uncaught exception:  UNKNOWN EXCEPTION
In file: ../../../../src/sysc/kernel/sc_except.cpp:107
In process: NoC.Tile[02][00]_(#2).Router.txProcess @ 1007 ns

repeating one more time:
....
....
In process: NoC.Tile[02][03]_(#14).Router.txProcess @ 1018 ns

And after repeating 3-4 times it returns this error:
       SystemC 2.3.1-Accellera --- Apr 12 2017 10:36:33
        Copyright (c) 1996-2014 by all Contributors,
        ALL RIGHTS RESERVED
                Noxim - the NoC Simulator
                (C) University of Catania

Loading configuration from file "../config_examples/default_config.yaml"... Done
Loading power configurations from file "power.yaml"... Done
Reset for 1000 cycles...
 done! Now running for 10000 cycles...
noxim: ../src/selectionStrategies/Selection_RANDOM.cpp:15: virtual int Selection_RANDOM::
apply(Router*, const std::vector<int>&, const RouteData&): Assertion `directions.size()!=0' failed.
Aborted (core dumped)

**Comment by davidepatti** [comment]
From the last message, it seems that your code does not provide a set of possible directions. You get different messages because there is probably something that depends on random seed.
First of all, try to use -seed option to repeat the same scenario. Then enable verbose logs (see slide 36 of https://github.com/davidepatti/noxim/blob/master/doc/noxim_tutorial.pdf)
