### ISSUE TITLE
Clearing signals of borderlines.

### ISSUE THREAD

**Issue by Rachel9595** [davidepatti/noxim#39]
Hi,
At file NoC.cpp we have the definition of tiles, map RX/TX signals and clearing signal for borderlines,

1- If we have [0][0], [1][0], [2][0], [3][0], ..., [mesh_X-1][0],  does the [i][j] node locate in "NORTH" borderline?

2- we have 2 signals (RX and TX) for each direction; "req[i][j].south" and "req[i][j].north":

	t[i][j]->req_rx[DIRECTION_NORTH] (req[i][j].south);
	t[i][j]->req_tx[DIRECTION_NORTH] (req[i][j].north);

For Clearing signals for borderline nodes, if we have request signal [i][0], why we clear just one signal (RX signal) for node located at NORTH borderline?
	req[i][0].south = 0; 

And why it doesn't need to clear TX signal (req[i][0].north) of the node located at NORTH borderline ?

And also we have this situation for three other borderlines.

Thank you for your time.

**Comment by davidepatti** [comment]
Anyway, just to close this issue, the cleaning of signals at border is not necessary. If the routing algorithm is working right, no outgoing/incoming signal toward/from not existing directions will ever be used.
