### ISSUE TITLE
Simulation does not run.

### ISSUE THREAD

**Issue by setat** [davidepatti/noxim#40]
Hi,
I have modified Noxim source and I have compiled it without any error. But when I run this command:

./noxim -config ../config_examples/default_config.yaml

 got this (configuration file and power configuration file , both loaded, but simulation did not execute):

  SystemC 2.3.1-Accellera --- Sep 12 2017 13:42:33
  Copyright (c) 1996-2014 by all Contributors,
  ALL RIGHTS RESERVED

          Noxim - the NoC Simulator
          (C) University of Catania

Loading configuration from file "../config_examples/default_config.yaml"... Done
Loading power configurations from file "power.yaml"... Done
Channel 0 data rate 8 Gbps, flit transmission delay 4000 ps, (aligned to 4000 ps) 4 cycles

**Comment by HassanMortazavi** [comment]
Hi 
Maybe you modify some of parts in default config file .
You can delete noxim directory and clone it again from main repository and try again.

Regards
