### ISSUE TITLE
routing algorithm winoc 

### ISSUE THREAD

**Issue by David6386** [davidepatti/noxim#41]
Hi,
How does Routing Algorithm Wireless Network On chip in Noxim Simulation work?  And this section in which source codes of Noxim Simulation is located?

**Comment by HassanMortazavi** [comment]
Hi 
you can find it in "routingFunction" function in Router.cpp.

but for better use of wireless routing(and more flexible) i commented it from Router.cpp and move it to my RoutingAlgorithm 
Regards
