### ISSUE TITLE
changing the power.yaml file.

### ISSUE THREAD

**Issue by setat** [davidepatti/noxim#43]
Hi,
If I want to increase the number of hubs without changing the number of nodes(Tiles) (for example 6 hubs), How can I achieve the information to change below part of power.yaml file:
......
tx_attenuation_map:
        #   - [TX Hub ID, RX Hub ID, Attenuation]
            - [0, 1, 1.1]
            - [0, 2, 2.2]
            - [0, 3, 3.3]
            - [1, 0, 1.0]
            - [1, 2, 2.2]
            - [1, 3, 3.3]
            - [2, 0, 1.0]
            - [2, 1, 1.1]
            - [2, 3, 3.3]
            - [3, 0, 1.0]
            - [3, 1, 1.1]
            - [3, 2, 2.2]

**Comment by davidepatti** [comment]
This information should be related to attenuation that your power model assumes between a given couple of hubs.  If you add hubs or change their position you should use some model to provide those numbers or ignore the effect.
