### ISSUE TITLE
Segmentation Fault on trying to run example from the article

### ISSUE THREAD

**Issue by augusto2112** [davidepatti/noxim#48]
I'm trying to run a slightly modified default_config.yaml as in the article but I keep getting segmentation faults. I'm using Ubuntu and installed noxim using the quick start option (bash <(wget -qO- --no-check-certificate https://raw.githubusercontent.com/davidepatti/noxim/master/other/setup/ubuntu.sh))

I have use_winoc = true

and:

    0:
        rxChannels: [0, 2]
        txChannels: [0, 2]
        attachedNodes: [0,1,4,5]

    1:
        rxChannels: [0, 1]
        txChannels: [0, 1]
        attachedNodes: [2,3,6,7]

    2:
        rxChannels: [2, 3]
        txChannels: [2, 3]
        attachedNodes: [8,9,12,13]

    3:
        rxChannels: [1, 3]
        txChannels: [2, 3]
        attachedNodes: [10,11,14,15]

This gave me a segmentation fault on "std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(char const*) const 0x00007ffff77c8430" inside the attachHub function.

If I add different channels like so:
    0:
        dataRate: 8
    1:
        dataRate: 8
    2:
[my_config .txt](https://github.com/davidepatti/noxim/files/1464703/my_config.txt)

        dataRate: 8
    3:
        dataRate: 8

I get another segmentation fault on updateTokenPacketRing.

I've attached the file as a txt because github doesn't accept yaml file
[my_config .txt](https://github.com/davidepatti/noxim/files/1464706/my_config.txt)

**Comment by davidepatti** [comment]
Multiple channels per hub are still under development/debugging.
Please use a single channel (and remove other channel description too)
`    0:
        rxChannels: [0]
        txChannels: [0]
        attachedNodes: [0,1,4,5]

    1:
        rxChannels: [0]
        txChannels: [0]
        attachedNodes: [2,3,6,7]

    2:
        rxChannels: [0]
        txChannels: [0]
        attachedNodes: [8,9,12,13]

    3:
        rxChannels: [0]
        txChannels: [0]
        attachedNodes: [10,11,14,15]`
