### ISSUE TITLE
 Butterfly Topology

### ISSUE THREAD

**Issue by SIRINE7878** [davidepatti/noxim#49]
Hello ,
Noxim use the topo mesh as default and I want to support butterfly topology. Thus I must change the code (e.g. signals mapping when creating the NoC). However, as a beginner in SystemC platform  it is difficult to understand code because noxim use advance system level coding. So I am unable to solve that and I am asking for this NoC Topology.
If you can give any clue or closest stuff will be well appreciated. .
Thanks in Advance.

**Comment by davidepatti** [comment]
Sorry, issues sections is dedicated only to particular bugs or doubts related to noxim.
