### ISSUE TITLE
gdb noxim

### ISSUE THREAD

**Issue by stdoo** [davidepatti/noxim#51]
Hi,
How to debug noxim with gdb? I try to debug the executable file，when I use a **list** command, the gdb just list the code belong to another source file, like this:
`❯ **gdb noxim**
Password:

GNU gdb (GDB) 8.0.1

Copyright (C) 2017 Free Software Foundation, Inc.

License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

This is free software: you are free to change and redistribute it.

There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.

This GDB was configured as "x86_64-apple-darwin17.0.0".

Type "show configuration" for configuration details.

For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.

Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".

Type "apropos word" to search for commands related to "word"...
Reading symbols from noxim...done.

**(gdb) list**
1	#include "Selection_RANDOM.h"
2	
3	SelectionStrategiesRegister Selection_RANDOM::selectionStrategiesRegister("RANDOM", getInstance());
4	
5	Selection_RANDOM * Selection_RANDOM::selection_RANDOM = 0;
6	
7	Selection_RANDOM * Selection_RANDOM::getInstance() {
8		if ( selection_RANDOM == 0 )
9			selection_RANDOM = new Selection_RANDOM();
10	    
(gdb) `
The code belongs to _/noxim/src/selectionStrategies/Selection_RANDOM.cpp_, can't figure out why this happened.

I try to set breakpoint in gdb, but it can't stop the execution of noxim, maybe the breakpoint is in Selection_RANDOM.cpp. Then how can I debug noxim with gdb?

**Comment by davidepatti** [comment]
Launching "gdb noxim" doesn't make noxim begin the execution.
You should type some gdb command like "run". You should also pass command line parameters to noxim.
Anyway, I don't think gdb is a good way for debugging noxim. Even I and the other noxim developers  never used it, we did everything with some "cout" and assert() inside the code.
