### ISSUE TITLE
Simulator not working properly

### ISSUE THREAD

**Issue by shubhamnath2** [davidepatti/noxim#58]
Simulator is only working for only XY routing algorithm and only for random traffic. Showing error:
noxim: ../src/Router.cpp:146: void Router::txProcess(): Assertion `false' failed.
Aborted (core dumped)

**Comment by asrani** [comment]
it works perfectly for me ..

**Comment by shubhamnath2** [comment]
@asrani Maybe your Simulator is not updated, check it once, cause for my case, the simulator is working for XY routing not for west first, north last, etc.

**Comment by davidepatti** [comment]
Hi to all, mine is working. 
Can you tell me how to replicate the problem ? (e.g., which yaml config are you using ?)

**Comment by shubhamnath2** [comment]
default_config.yaml

**Comment by shubhamnath2** [comment]
Then I replaced the new files with the old one(without vc) and compiled it,
now it's working.
(I am currently working on ubuntu 16.04 and after march update, this
problem arise)

**Comment by davidepatti** [comment]
I just took the original default_config.yaml, I replaced XY with WEST_FIRST. It works. Are you sure you are using the latest version on github ?

**Comment by davidepatti** [comment]
Ok, I managed to replicate the issue. I'll let you know asap.

**Comment by davidepatti** [comment]
The problem should be now solved in the latest github version.
Just do a "git pull" from src directory and recompile, or reinstall.

**Comment by shubhamnath2** [comment]
I'll look into it, thank you for the help.

**Comment by davidepatti** [comment]
thank you for reporting the issue. 
I forgot to merge to merge the updates from the latest experimental branch to the main tree.
Everything worked on my local copy because I did not pushed to the github.
My fault, thank you again !

**Comment by shubhamnath2** [comment]
Thank you for solving the issue, currently i didn't check the correction(don't want to take risk on my system), but i'll look into it.

**Comment by shubhamnath2** [comment]
Thank you for solving the issue, currently i didn't check the correction(don't want to take risk on my system), but i'll look into it
