### ISSUE TITLE
A question about multicast

### ISSUE THREAD

**Issue by CLAY2333** [davidepatti/noxim#63]
Hi there..
       I am a college student from China and I am using noxim to complete my curriculum design. But I don't quite understand how to implement a multicast routing algorithm on noxim. Can you guide me or have a simple example?
                                                                                                                                                Thanks in CLAY

**Comment by davidepatti** [comment]
Hi, 
we have no examples, but you could simply add a new field in the TPacket  type, managing it properly in your own routing code.

**Comment by CLAY2333** [comment]
Hi,
Thank you for your answer, but I did not find the TPacket field in the source code, I do not know which file it is in. I do not know how to control the target routing table. I hope you can give me some answers, thank you
