### ISSUE TITLE
Memory module

### ISSUE THREAD

**Issue by Jiji10** [davidepatti/noxim#68]
Dear Mr,

I notice that there is not a memory module in the implementation of NoC in the Noxim.  Does the tile have a memory module? Am I missing something?

Please advice
Thanks

**Comment by davidepatti** [comment]
Noxim assumes a message passing traffic between nodes. Which kind of module are you referring to ? a local cache ? a memory controller ?

**Comment by Jiji10** [comment]
Yes, a memory controller. Can i add this module ?
