### ISSUE TITLE
New algorithm integration to the Noxim Simulator.

### ISSUE THREAD

**Issue by NavonilChatterjee** [davidepatti/noxim#73]
I have developed a new routing algorithm called WHIRL. I have followed the steps in the Noxim tutorial. 
However, when I have done make clean and make, the following error is coming. Please help.

Loading configuration from file "../config_examples/test_noxim.yaml"... Done
Loading power configurations from file "power.yaml"...
Error: (E549) uncaught exception: yaml-cpp: error at line 72, column 6: end of map not found
In file: ../../../../src/sysc/kernel/sc_except.cpp:100

In the power.yaml

  62    routing:
  63     #   Algorithm:   [Static, Dynamic]
  64          default:     [1.20e-4, 6.00e-14]
  65          XY:          [1.20e-4, 6.00e-14]
  66         DYAD:        [1.35e-4, 6.75e-14]
  67          NEGATIVE_FIRST: [1.28e-4, 6.30e-14]
  68          NORTH_LAST:  [1.28e-4, 6.30e-14]
  69         WEST_FIRST:  [1.28e-4, 6.30e-14]
  70          ODD_EVEN:    [1.32e-4, 6.60e-14]
  71          TABLE_BASED: [2.40e-4, 12.00e-14]
  72	        WHIRL:	[1.30e-4, 6.20e-14]

**Comment by davidepatti** [comment]
could you please attach your power.yaml and configuration.yaml files ?
