### ISSUE TITLE
Not an issue, but a python extension: Pynoxim - python script for noxim

### ISSUE THREAD

**Issue by rounaksingh** [davidepatti/noxim#77]
Hi @davidepatti ,
As part of my course project I have written a small python script to run noxim and plot graphs directly. It does not uses a python bindings but already complied noxim binary. If I will have time I might work on bindings. But right now, this is all I have. 

https://github.com/rounaksingh/pynoxim

Requires:
>Python3.5
Matplotlib
pyyaml
numpy

May be it might be useful for someone. Let me know what you think of it.

Thanks!

**Comment by davidepatti** [comment]
Dear @rounaksingh ,
it seems very useful and interesting. Thank you for your contribution. I will checkout its usage with some students here at university.
