### ISSUE TITLE
buffer occupancy 

### ISSUE THREAD

**Issue by saipriya-ar** [davidepatti/noxim#79]
how to calculate buffer occupancy in noxim 
i am going to implement IEEE paper "Local Congestion avoidance in network on chip"
can you please help me out 
thanks in advance

**Comment by davidepatti** [comment]
Just look at the Buffer.h file, some already existing function as:
  unsigned int getCurrentFreeSlots() const;

could be useful.

**Comment by Leiyulin** [comment]
hello. the error message you pasted shows that it can't find systemc.h which include in systemc-$version/lib-linux64. please check 1)whether you'v installed systemc successfully,2)did you modify the Makefile with proper yaml-cpp and systemc installation path? good luck.

**Comment by vakh1375** [comment]
hello. In buffer.cpp we can get buffer state (with printing push, pop, and front) but i think these buffers must be a FIFO memory! not like a stack. now can you please explain what is happening in these buffer? what is meaning of "pop" and "front" in this code.
i have another question. can i change "sc_start" function? (where is this function? witch file?) if it is not possible, how can i get system clock in buffer.cpp functions? and how can i get PE local buffer? in your examples, four buffer defined for any router. if i need to declare a buffer for Processing element (that connected to router), what should i do?
thanks a lot :)
