### ISSUE TITLE
Real workloads.

### ISSUE THREAD

**Issue by setat** [davidepatti/noxim#88]
Hi,
I want to try simulation by real workloads like Splash2 benchmarks (FFT, Radix, LLU,...) or PARSEC (Blackholes, Canneal, ..) in Noxim.
Is it possible at this time?
I am wondering if you could guide me How I can do this. 
Thanks a lot.

**Comment by davidepatti** [comment]
You could implement a traffic trace based packet generation, or use traffic table to characterize some data flows correspoding to the real application's data flows.
