### ISSUE TITLE
How to modified noxim for prediction

### ISSUE THREAD

**Issue by Prince-Fash** [davidepatti/noxim#91]
Can anybody explain how Noxim can be coded to predict traffic flow in Wireless Routers.
How noxim cam be link or programme with Artificial Neural Network
?????
what can I do to Run Noxim simulator with ANN for prediction.......

Thank you all.

**Comment by davidepatti** [comment]
These questions are too generic and each of them represent a potential long term activity, so make no sense to manage them as "issues".
