### ISSUE TITLE
how to make systemC project in eclipse?

### ISSUE THREAD

**Issue by RanaKarem** [davidepatti/noxim#92]
i'm trying to install a network-on-chip simulator on windows (noxim, noctweak) ....i installed systemc and GCC and now i'm trying to compile the source code of the simulator in systemc

but it always gives me that error <<systemc.h: No such file or directory>> when i build

**Comment by davidepatti** [comment]
I don't know in Eclipse, but in https://github.com/davidepatti/noxim/blob/master/other/setup/README_CLion.txt
you will find instruction for executing in CLion, the beautiful IDE from jetbrains (win,macosx, linux)
