### ISSUE TITLE
NoCTweak

### ISSUE THREAD

**Issue by RanaKarem** [davidepatti/noxim#94]
I'm new to on-chip simulators specially NoCTweak....I read the paper of the author "NoCTweak a Highly Parameterizable Simulator for Early Exploration of Performance and Energy of Networks On-Chip"and trying to apply the examples to run the simulator and display the output numerically and by graphs .
I ran the code example and displayed the numerical results in (output.log) but when trying to view the graphs in (waveform.vcd)....it keeps loading and nothing appears can anyone help?

**Comment by davidepatti** [comment]
This project is not about NocTweak but Noxim.
