### ISSUE TITLE
Issues about table based traffic

### ISSUE THREAD

**Issue by zby5558** [davidepatti/noxim#96]
I want to use the table based traffic in noxim. But I can not find any example of the txt file. Could someone show an example for me?

**Comment by KRISHNADAIVAJNA** [comment]
Even I am trying to get info about the same. Any help would be great.

**Comment by van-namdinh** [comment]
me too!

**Comment by KacperKubara** [comment]
Possible duplicate of https://github.com/davidepatti/noxim/issues/50

**Comment by AntiHackerir** [comment]
the first node id is "0"
and the last id node is "n-1"

[source] [destination] [pir]
example :

0 8
3 1
8 6 0.1
2 4 0.2

and etc...
