### ISSUE TITLE
Energy consumed on links

### ISSUE THREAD

**Issue by Jiji10** [davidepatti/noxim#98]
Hi,
In "bin/power.yaml" , Static and Dynamic power consumption are defined for different length of links.  I need to compute the power consumption for other length of links ( < 0.5 mm):

In power.yaml:
 LinkBitLine:
    #   - [ Length (mm), Leakage, Dynamic ] 
        - [0.5, 4.76e-7, 2.50e-14]
        - [1.0, 4.80e-7, 4.88e-14]
        - [1.5, 4.92e-7, 7.25e-14]
        - [2.0, 5.10e-7, 9.63e-14]
        - [2.5, 5.50e-7, 1.20e-13]
        - [3.0, 5.53e-7, 1.43e-13]

Would you please explain the mechanism of computation of power consumption of links in Noxim simulaor ?

Thanks.

**Comment by davidepatti** [comment]
you should interpolate or recompute the values by yourself. Or taking them from literature.
